name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.2' # The version from gradle-wrapper.properties

    - name: Build with Gradle
      # We use 'gradle' directly instead of './gradlew' to bypass the need for local wrapper files
      run: gradle :app:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cinemix-app-release
        path: app/build/outputs/apk/release/app-release.apk
